### ISSUE TITLE
Rest API Deposit History returns empty: despite having deposit history, it returns []

### ISSUE THREAD

**Issue by invaliddayta** [ln-markets/api-python#10]
Issue Description:
The Rest API's Deposit History feature is not functioning as expected. Although the withdraw and funding history endpoints successfully return values, the deposit history endpoint returns an empty response (i.e., []). However, there is clearly a deposit history present.

Steps to Reproduce:

Make a GET request to the Deposit History endpoint using the appropriate API endpoint.
Review the response received.
Expected Behavior:
The Deposit History endpoint should return a list of deposit records that match the specified parameters, containing relevant details such as deposit ID, date, amount, and transaction status.

Actual Behavior:
The Deposit History endpoint returns an empty response ([]), indicating that there are no deposit records available. However, this is incorrect as there are verified deposits present in the system.

Additional Information:

The withdraw and funding history endpoints work correctly and provide the expected data.
The API key used for authentication has appropriate permissions to access deposit history.
The issue has been observed consistently across multiple attempts.

API Version 2.0.1

Possible Solution:
Investigate and troubleshoot the Deposit History endpoint to identify any issues causing the empty response. Verify that the necessary data is being correctly fetched and returned from the database or backend system. Review the API code logic and ensure that it is properly handling and returning deposit history records. Perform comprehensive testing to validate the solution before deploying any changes.

**Comment by RomainRouphael** [comment]
Hey, thanks for this very detailed issue, much appreciated!

We're on it, we will keep you posted.

All the best

**Comment by RomainRouphael** [comment]
Ok, glitch identified with our API.

You have to specify the 3 params (for example params = {'from': 0, 'to': 1686916367000, 'limit': 5}) and call lnm.deposit_history(params) to make it work.

So you can do that to get your deposit history now.

Meanwhile, we are pushing a fix on the API so that params are optionals, as they are for withdraw.

Thank you!

**Comment by invaliddayta** [comment]
Thank you for the quick fix much appreciated 😁
