### ISSUE TITLE
WebSockets not able to subscribe / list methods / list events

### ISSUE THREAD

**Issue by pythcoiner** [ln-markets/api-python#11]
here my snippet:
```python
from lnmarkets import websockets
import config


class WS(websockets.LNMarketsWebsocket):
    def __init__(self, **options):
        super().__init__(**options)

    def on_open(self, ws):
        print("Opened connection")
        self.subscribe(["futures/market/bid-offer"])
        self.list_methods()
        self.list_events()


options = {'key': config.lnmarkets['key'],
           'secret': config.lnmarkets['secret'],
           'passphrase': config.lnmarkets['passphrase'],
           'network': 'mainnet'}

lnm = WS(**options)
lnm.connect()
```

I got this output:
```shell
Opened connection
{"jsonrpc":"2.0","id":"515e369f","error":{"code":-32601,"message":"Not Found","data":{"reason":"There is no JSON RPC method named subscribe"}}}
{"jsonrpc":"2.0","id":"46ae2c18","error":{"code":-32601,"message":"Not Found","data":{"reason":"There is no JSON RPC method named __listMethods"}}}
{"jsonrpc":"2.0","id":"4263812c","error":{"code":-32601,"message":"Not Found","data":{"reason":"There is no JSON RPC method named __listEvents"}}}

```

**Comment by RomainRouphael** [comment]
Hey, thanks for your message!

The new method to connect to websocket is:
- method = 'v1/public/subscribe'
and the subscription parameters:
-     subscribe_params = [
        'futures:btc_usd:last-price',
        'futures:btc_usd:index'
    ]

The doc will be updated soon to reflect these changes.

All the best,
Romain

**Comment by RomainRouphael** [comment]
I pushed a new version of the python connector to take into account these changes and updated the doc of this repo.

Here is how to install the latest version of the package: https://pypi.org/project/ln-markets/2.0.2/

Then this code will work

`from lnmarkets import websockets

options = {'key': key, 
           'secret': secret, 
           'passphrase': passphrase}

subscribe_params = [
        'futures:btc_usd:last-price',
        'futures:btc_usd:index'
    ]

class WS(websockets.LNMarketsWebsocket):
    def __init__(self, **options):
        super().__init__(**options)

    def on_open(self, ws):
        print("Opened connection")
        self.subscribe(subscribe_params)
        self.list_methods()
        self.list_events()


lnm = WS(**options)
lnm.connect()

 `

**Comment by pythcoiner** [comment]
merci Romain

**Comment by pythcoiner** [comment]
I just had a try, subscribe is working now, but still issue on list_methods(), and list_events():
```shell
Opened connection
{"jsonrpc":"2.0","id":"2594b317","result":["futures:btc_usd:last-price","futures:btc_usd:index"]}
{"jsonrpc":"2.0","id":"6f744170","error":{"code":-32601,"message":"Not Found","data":{"reason":"There is no JSON RPC method named __listMethods"}}}
{"jsonrpc":"2.0","id":"581a38cf","error":{"code":-32601,"message":"Not Found","data":{"reason":"There is no JSON RPC method named __listEvents"}}}
{"jsonrpc":"2.0","method":"subscription","params":{"channel":"futures:btc_usd:index","data":{"index":29941.42,"time":1690016160804}}}
{"jsonrpc":"2.0","method":"subscription","params":{"channel":"futures:btc_usd:index","data":{"index":29940.91,"time":1690016165803}}}
{"jsonrpc":"2.0","method":"subscription","params":{"channel":"futures:btc_usd:index","data":{"index":29940.94,"time":1690016170803}}}
```

**Comment by RomainRouphael** [comment]
Thanks, I don't think they're available anymore.
Our API doc will be updated promptly according to the latest version of our API.
Thank you!
