### ISSUE TITLE
Invalid request response from rest API, get_trade

### ISSUE THREAD

**Issue by EdwardHodl** [ln-markets/api-python#13]
I was trying out the REST get_trade API but the response is always "Invalid Request"

{"message":"Invalid request","issues":[{"code":"invalid_type","expected":"void","received":"object","path":[],"message":"Expected void, received object"}]}

The API is quite simple and I don't believe my request is invalid.
https://docs.lnmarkets.com/api/operations/futuresgettrade

Does this API require authentication in the library? 
https://github.com/ln-markets/api-python/blob/5d05b4cb1e575f0ab6252663958151826b420cff/lnmarkets/rest.py#L219-L225

**Comment by RomainRouphael** [comment]
Hey,
Indeed, that's strange, I tried without or with authentication but gets the same error.
I'll dig deeper and come back to you on this!
Cheers

**Comment by RomainRouphael** [comment]
Hello,

This should be fixed now.

Thanks for your patience,
Romain
