### ISSUE TITLE
futures_close_all() fails often, a bug? 

### ISSUE THREAD

**Issue by immartian** [ln-markets/api-python#15]
We call futures_close_all() sometimes in our program but it fails many times with no error code returned. Wonder if there's anything wrong at the backend endpoint. 

https://github.com/ln-markets/api-python/blob/4c4bed1ce04ced749cebebf2bc1bdc9c58d363ae/lnmarkets/rest.py#L133

**Comment by RomainRouphael** [comment]
Hey,

Have you tried updating to the latest version of the connector?
It should fix the issue.

Thanks,
Romain

**Comment by immartian** [comment]
thanks for pointing that, I will try and update.
