### ISSUE TITLE
get_user returns ''Your request too far in the future" error.

### ISSUE THREAD

**Issue by wintercooled** [ln-markets/api-python#3]
Signing in with API key I've already used with no issue I get the error:

`{"code":"apiKeyTimestampTurfu","message":"Your request too far in the future"}`

**Comment by wintercooled** [comment]
Seems to work now. Nothing changed my end.

**Comment by wintercooled** [comment]
Closing as assume it was a temporary thing your end?

**Comment by wintercooled** [comment]
Happening again today. Any idea what causes this?

**Comment by wintercooled** [comment]
Happening again today. Any idea what causes this?

**Comment by RomainRouphael** [comment]
Hey, thank you!
The reason for this error is when you are using a timestamp > to now (current timestamp).
Any idea why this would happen?
I don't manage to reproduce this error yet.

**Comment by wintercooled** [comment]
I'm using a virtual machine (Ubuntu 20.04) if that helps - although I can't se why that would matter - it updates system clock on start up like any machine would. I'm on GMT here, perhaps it is something to do with when I'm running it if my machine is a day ahead of yours (in terms of the day of the month) and you aren't taking timezones like that into account?

**Comment by RomainRouphael** [comment]
Hey,
Our servers timestamp are on GMT as well..
